### ISSUE TITLE
Setup on Ubuntu 18.04

### ISSUE THREAD

**Issue by sebmarchand** [Chia-Network/clvm_tools#72]
Hi,

This isn't really a bug but I recently had some issues getting a functional clvm environment on my server running Ubuntu 18.04 and I thought that I should share the steps that I had to follow here.

First I've wasted a lot of time trying to make things work without really checking the version of Python I was using. Turns out that I was using python 3.6 and that IIUC for the blspy dependency to be resolved properly you need at least 3.7.

Then I still had a few issues, here's the commands I had to run:
```
git clone https://github.com/Chia-Network/clvm_tools.git
cd clvm_tools
python3 -m venv clvm_env
. ./clvm_env/bin/activate
pip install -e .
git clone https://github.com/Chia-Network/clvm.git
cd clvm
python3 -m venv venv
. ./venv/bin/activate
pip install -e '.[dev]'
cd ..
run '(mod ARGUMENT (+ ARGUMENT 3))'
```

I could probably create only one venv but once I got it to work I focused on playing with Chialisp :).

Let me know if you want me to try something, I really believe that providing some really clear setup instructions that work on all platforms will help with the adoption of Chialisp.

Thanks

**Comment by roschler** [comment]
In addition to @sebmarchand 's instructions, I also had to do the steps shown below so that the command `python3` went to my newly installed 3.7 version and not the previous 3.6 version.  Then I had to install `python3.7-venv` too.  Without that last step I got errors when I tried to create a virtual environment:
```
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
sudo update-alternatives --config python

sudo apt install python3.7-venv
```

**Comment by wallentx** [comment]
Closing old issue
